accounts/urls.py
from django.conf.urls import url,include
from . import views
from django.shortcuts import redirect
from django.contrib.auth import views as auth_views
from django.conf import settings

urlpatterns =[
    url(r'^login/$',auth_views.login,name='login',kwargs={'template_name': 'accounts/login.html'}),
    url(r'^logout/$',auth_views.logout,name='logout', kwargs={'next_page': settings.LOGIN_URL}),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^profile/$',views.profile,name='profile'),
]

baemin/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.shortcuts import redirect

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('shop.urls',namespace='shop')),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^$',lambda x:redirect('shop:index'),name='root')
]

shop/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import *
urlpatterns = [

    url(r'^index/$',index_view,name='index'),
    url(r'^baemin/(?P<pk>\d+)/new/',order_view,name='order'),
]

accounts/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


class Shop(models.Model):
    name = models.CharField(max_length=100)                # 이름
    tel =  models.CharField(max_length=100)                 # 전화번호
    addr = models.CharField(max_length=100)   # 주소

    def __str__(self):
        return self.name

class Item(models.Model):
    shop = models.ForeignKey(Shop)                # 가게
    name = models.CharField(max_length=100)                 # 이름
    price = models.CharField(max_length=100)                # 가격

    def __str__(self):
        return self.name

class Order(models.Model):
    shop = models.ForeignKey(Shop)                 # 가게
    user = models.ForeignKey(settings.AUTH_USER_MODEL)                 # 주문한 유저
    item_set = models.ManyToManyField(Item)             # 주문한 상품 목록 (Hint: ManyToManyField)
    created_at = models.DateTimeField(auto_now=True)           # 생성일시

    def __str__(self):
        return self.user

    @property
    def order_sum(self):
        result= sum(int(item.price) for item in self.item_set.all())
        return result
# Create your models here.

shop/forms.py
from .models import Item,Shop,Order
from django import forms


class OrderModelForm(forms.ModelForm):
    def __init__(self, shop, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.shop = shop
        self.fields['item_set'].queryset = self.fields['item_set'].queryset.filter(shop=shop)


    class Meta:
        model = Order
        fields = ('item_set',)

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from shop.models import Shop,Item,Order
from shop.forms import OrderModelForm
# Create your views here.

def signup(request):
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = UserCreationForm()

    return render(request,'accounts/signup_form.html',
                  {'form':form
            })

@login_required
def profile(request):
    user= request.user
    my_order = Order.objects.filter(user=user).all()

    return render(request,'accounts/profile.html',{
        'user':user,
        'order_list':my_order,
    })

shop/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Shop,Item,Order
from .forms import OrderModelForm
from django.contrib.auth.decorators import login_required

def index_view(request):
    shop = Shop.objects.all()
    return render(request,'shop/index.html',{
        'shops':shop
    })

@login_required
def order_view(request,pk):
    shop = get_object_or_404(Shop, id=pk)
    item_price = Item.objects.filter(shop=shop).all()
    if request.method =='POST':
        form = OrderModelForm(shop,request.POST)
        if form.is_valid:
            order = form.save(commit=False)
            order.user = request.user
            order.shop = shop
            order.save()
            form.save_m2m()
            return redirect('accounts:profile')
    else:
        form= OrderModelForm(shop)

    return render(request,'shop/order.html',{
        'order_form':form,
        'shop':shop,
        'item_price':item_price,
    })
# Create your views here.

accounts/templates/accounts/layout.html
{% extends 'layout.html' %}
{% block title %}
    {% block contents %}
    {% endblock %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/layout.html' %}
{% block contents %}
    <h1> 로그인 </h1>
    <form action="" method="post">
        <table>
            {% csrf_token %}
            {{ form.as_table }}
        </table>
        <input type="submit">
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/layout.html' %}}
{% block contents %}
    <h1>{{ user }}의 프로필</h1>

    <h4>주문내역 (TODO)</h4>

    <table>
        <thead>
            <tr>
                <th>가게명</th>
                <th>주문상품</th>
                <th>총액</th>
                <th>주문일시</th>
            </tr>
        </thead>
    {% if order_list %}
        <tbody>
            {% for order in order_list %}
            <tr>
                <td>{{ order.shop.name }}</td>
                <td>
                    {% for item in order.item_set.all %}
                        {{ item.name }}
                    {% endfor %}
                </td>
                <td>{{ order.order_sum }}</td>
                <td>{{ order.created_at }}</td>
            </tr>
            {% endfor %}
        </tbody>
    {% else %}
    </table>
        <h3>주문내역이 없습니다</h3>

    {% endif %}

{% endblock %}

accounts/templates/accounts/signup_form.html
{% extends 'accounts/layout.html' %}
{% block contents %}
    <form action="" method="post">
        <table>
            {% csrf_token %}
            {{ form.as_table }}
        </table>
        <input type="submit">
    </form>
{% endblock %}

baemin/templates/layout.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>벤처창업웹프로그래밍2 - 2017</title>
    </head>
    <body>
        <a href="{% url 'shop:index' %}"><h1>먹방의 민족 - 우리동네 배달 지도</h1></a>
        {% if user.is_authenticated %}
            <a href="{% url 'accounts:profile' %}">{{ user }}'s 프로필 </a>
            <a href="{% url 'accounts:logout' %}?next={{ request.path }}">로그아웃</a>
        {% else %}
            <a href="{% url 'accounts:login' %}?next={{ request.path }}">로그인</a>
            <a href="{% url 'accounts:signup' %}">회원가입</a>
        {% endif %}
    {% block title %}
    {% endblock %}
    </body>
</html>

shop/templates/shop/index.html
{% extends 'shop/layout.html' %}
{% block contents %}
    <table>
    <thead>
        <tr>
            <th>가게명</th>
            <th>전화번호</th>
            <th>주소</th>
            <th>주문하기</th>
        </tr>
    </thead>
    <tbody>

    </tbody>
        {% for shop in shops %}
        <tr>
            <td>{{ shop.name }}</td>
            <td>{{ shop.tel }}</td>
            <td>{{ shop.addr }}</td>
            <td><a href="{% url 'shop:order' shop.id  %}">주문하기</a></td>  <!-- 아래 항목에서 구현 예정 -->
        </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}

shop/templates/shop/layout.html
{% extends 'layout.html' %}
{% block title %}
    {% block contents %}
    {% endblock %}
{% endblock %}

shop/templates/shop/order.html
{% extends 'shop/layout.html' %}
{% block contents %}
    <h2>{{ shop.name }} 주문하기</h2>
    <form action="" method="POST">
    {% csrf_token %}
        <table>
            {{ order_form.as_table }}
        </table>
        <table>
            {% for item in item_price %}
            <li>{{ item.name }} : {{ item.price}}</li>
            {% endfor %}
        </table>
        <input type="submit">
    </form>
{% endblock %}